In [1]:
import pandas as pd
import numpy as np

In [2]:
list1 = [10, 20, 30]
list1

[10, 20, 30]

In [3]:
arr1 = np.array(list1)
arr1

array([10, 20, 30])

In [4]:
type(arr1)

numpy.ndarray

In [5]:
# nd - n-Dimensional

In [8]:
arr2 = np.arange(10,20, 1)
arr2

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19])

In [10]:
list2 = [40, 50, 60]

In [11]:
list3 = [list1, list2]
list3

[[10, 20, 30], [40, 50, 60]]

In [13]:
arr3 = np.array(list3)
arr3

array([[10, 20, 30],
       [40, 50, 60]])

In [14]:
arr3.shape

(2, 3)

In [16]:
arr3dim = np.array(
    [
        [
            [1,2 ,3], [3, 4, 5]            
            
        ],
        [
            [5, 6 ,7], [7, 8, 9]
        ]
    ]

)
arr3dim

array([[[1, 2, 3],
        [3, 4, 5]],

       [[5, 6, 7],
        [7, 8, 9]]])

In [17]:
arr3dim.shape

(2, 2, 3)

In [18]:
arr3dim * 3

array([[[ 3,  6,  9],
        [ 9, 12, 15]],

       [[15, 18, 21],
        [21, 24, 27]]])

In [19]:
arr2 = np.array(list2)

In [20]:
arr1 * arr2

array([ 400, 1000, 1800])

In [25]:
list1 = [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12]
arr1 = np.array(list1)
arr1.shape

(12,)

In [26]:
list2 = [
    [1, 2, 3 , 4],
    [1, 2, 3, 4], 
    [1, 2 ,3, 4] 
]
arr2 = np.array(list2)
arr2.shape

(3, 4)

In [30]:
arr3dim = np.array(
    [
        [
            [1,2 ,3,4], [1, 2, 3, 4], [1, 2, 3, 4], [1, 2, 3, 4], [1, 2, 3, 4]              
            
        ],
        [
            [1, 2, 3, 4], [1, 2, 3, 4], [1, 2, 3, 4], [1, 2, 3, 4], [1, 2, 3, 4]  
        ],
    
    ]

)
arr3dim.shape

(2, 5, 4)

In [31]:
np.zeros((12, ))

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [32]:
np.ones((2, 5, 4))

array([[[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]],

       [[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]]])

In [33]:
arr3

array([[10, 20, 30],
       [40, 50, 60]])

In [35]:
np.array(list3, dtype = float)

array([[10., 20., 30.],
       [40., 50., 60.]])

In [36]:
arr1[1]

2

In [37]:
arr3[1][2]

60

In [38]:
arr3[1,2]

60

In [39]:
arr3[0]

array([10, 20, 30])

In [40]:
arr3[:,1]

array([20, 50])

In [41]:
arr3dim[1,1, 0]

1

In [43]:
arr3dim[:,:,: 1]

array([[[1],
        [1],
        [1],
        [1],
        [1]],

       [[1],
        [1],
        [1],
        [1],
        [1]]])

In [44]:
arr3dim.sum()

100

In [45]:
arr3dim.mean()

2.5

In [46]:
arr3dim.std()

1.118033988749895

In [47]:
arr3dim.mean(1)

array([[1., 2., 3., 4.],
       [1., 2., 3., 4.]])

In [48]:
arr3dim.var()
# squared deviation

1.25

In [49]:
arr3dim.min()

1

In [50]:
arr3dim.max()

4

In [51]:
for x in arr1:
    print(x)

1
2
3
4
5
6
7
8
9
10
11
12


In [52]:
for dim in arr3:
    for x in dim:
        print(x)

10
20
30
40
50
60


In [53]:
for x in np.nditer(arr3):
    print(x)

10
20
30
40
50
60


In [59]:
np.save("new_array", arr3)

In [61]:
np.load("new_array.npy")

array([[10, 20, 30],
       [40, 50, 60]])

In [62]:
np.savetxt("new_array.txt", arr3, delimiter='\t')